### ISSUE TITLE
Repository::HEAD() is flawed

### ISSUE THREAD

**Issue by scunz** [macgitver/libGitWrap#71] opened 2015-03-16 15:53 UTC
The Repository::HEAD() method is totally flawed. It always returns a reference object that reflects the _ObjectID_ of the HEAD branch, if such branch exists.

As a consequence, `Repository::headBranch()` and RepoMan's `Repo::branchDisplay()` are broken, too.

I _think_ this worked once, so this must have changed inside libgit2 itself at some point. For `RM::Head`, I introduced a new method in GitWrap which just gets the name of the HEAD branch if such exists.

Not sure how to deal with that. I'd like to simply deprecate HEAD() and remove all uses of it...

Thoughts? @antis81

**Comment by antis81** [comment] 2015-03-16 16:26
I just looked into libgit2's changelog and it doesn't state any API change to `git_repository_head`. Thus, I doubt, that it changed there.

You updated libgit2 recently. If this is caused by libgit2, this is the first place to look at. 

I don't know if we mean the same thing though. The behaviour used to be like this:
When detached, `Repository::HEAD()` returned a direct `HEAD` reference pointing to the ObjectId. When a (symbolic) HEAD pointed to the active branch, the actual branch (i.e. "refs/heads/master") was returned. This was exactly the behaviour of libgit2 `git_repository_head`.

For this reason I used `Repository::reference(r, "HEAD");`, which always just looks up HEAD without resolving it.

Hm, if you like to deprecated it, I'm pretty sure you do it for good reason. Currently I don't have a use case for it.

**Comment by scunz** [comment] 2015-03-16 16:33
I updated lg2? Can't remember. I only see that my local checkout seems to be inconsistent. However, the last official update to lg, was by you in 8c8667dcf170c866d54ac5f11dc72f1613d3bbbb.

>  When a (symbolic) HEAD pointed to the active branch, the actual branch (i.e. "refs/heads/master") was returned.

That's not entirely true, but it's the problem: It gets resolved into a non-symbolic reference that has no name attached to it (I debugged it deep into lg2).

So, I wasn't aware of the fact that you actually used `Repository::reference(r, "HEAD");` - But I guess that means it was flawed forever probably... Cheers to unit tests :)

**Comment by antis81** [comment] 2015-03-16 17:07
> So, I wasn't aware of the fact that you actually used Repository::reference(r, "HEAD"); - But I guess that means it was flawed forever probably... Cheers to unit tests :)

Hehe, yes we really need them to check those nasty algorithms still work the same way. Nevertheless: We have some more complex test scenarios where we need to setup a test environment. For example I have some unfinished local work here to test the `CommitOperation`. There are mainly two use cases:
- Create the root commit on a fresh repository.
- Do the common commit on top of the active branch.

The CommitOperation does not yet work (which might also be related to the crappy HEAD :). But the point here is, that to test these use cases, we need to prepare some defined tree-object in the index, which is turned into the actual commit. Any ideas how we can achieve this in a sane way?

**Comment by scunz** [comment] 2015-03-16 17:16
I'd suggest to look into lg2's CLAR tests. It might actually be a good idea for GitWrap to port all of the CLAR tests to our API, so we can be sure we've done everything right and not missed something...

**Comment by scunz** [comment] 2015-03-16 17:18
Btw.: I ported the `branchDisplay` to the new Head object in RM. And I actually think that I saw this work just a few days ago - So I might have broken it myself. However, I didn't touch _any_ code that is even remotely close to that code path and the implementation suggest that it should have never worked... Strange thing that is.

**Comment by antis81** [comment] 2015-05-18 19:20
This issue is solved, isn't it?

**Closed as completed by antis81** 2015-05-18 19:20 UTC
